# https://github.com/marketplace/actions/labeler
name: "Pull Request Labeler"
on:
  pull_request:
    types: [opened]

jobs:
  add-labels:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: TimonVS/pr-labeler-action@v4
      with:
        repo-token: ${{ secrets.GH_TOKEN }}
        configuration-path: '.github/config/labels.yml'