# https://github.com/marketplace/actions/labeler
name: "Auto Assign Labels"
on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  add-labels:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: TimonVS/pr-labeler-action@v4
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        configuration-path: '.github/config/labels.yml'