# https://github.com/marketplace/actions/auto-assign-action
name: Auto Assign Reviewers
on:
  pull_request:
    types: [opened, reopened, ready_for_review]

jobs:
  add-reviewers:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.2.5
        with:
          repo-token: ${{ secrets.GH_TOKEN }}
          configuration-path: '.github/config/reviewers.yml' 