name: jira-description-action
on:
  pull_request:
    types: [opened]
    branches: ['master', 'main']

jobs:
  add-jira-description:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: cakeinpanic/jira-description-action@v0.3.3
        name: jira-description-action
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          jira-token: ${{ secrets.JIRA_TOKEN }}
          jira-base-url: https://adeva.atlassian.net
          custom-issue-number-regexp: '^\d+' #optional
          jira-project-key: 'PLAT' #optional    
