name: jira-description-action
on:
  pull_request:
    types: [opened, edited]
    branches: ['master', 'main']

jobs:
  add-jira-description:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Jira Issue Details
        id: jiraGetIssue
        uses: fjogeleit/http-request-action@main
        with:
          url: 'https://adeva.atlassian.net/rest/api/3/issue/PLAT-2201?fields=summary'
          method: 'GET'
          customHeaders: '{"Authorization": "Basic ${{ secrets.JIRA_TOKEN }}"}'
      - name: Show Response
        run: |
          echo ${{ steps.jiraGetIssue.outputs.response }}
          echo ${{ steps.jiraGetIssue.outputs.headers }}
          echo ${{ fromJson(steps.jiraGetIssue.outputs.response).key }}

      - uses: seripap/pr-update-action@v3.1.2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          base-branch-regex: 'master|main'
          title-template: '[${{ fromJson(steps.jiraGetIssue.outputs.response).key }}]'
          body-template: 'https://adeva.atlassian.net/browse/${{ fromJson(steps.jiraGetIssue.outputs.response).key }}'
          title-update-action: 'prefix'
          body-update-action: 'prefix'

