name: jira-description-action
on:
  pull_request:
    types: [opened, edited]
    branches: ['master', 'main']

jobs:
  add-jira-description:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: cakeinpanic/jira-description-action@v0.4.0
        name: jira-description-action
        with:
          use: both
          github-token: ${{ secrets.GITHUB_TOKEN }}
          jira-token: ${{ secrets.JIRA_TOKEN }}
          jira-base-url: https://adeva.atlassian.net
          # custom-issue-number-regexp: '\d+' #optional
          jira-project-key: 'PLAT' #optional    
          fail-when-jira-issue-not-found: true
