# https://github.com/marketplace/actions/merge-branch
name: "Merge into develop on Approval"
on:
  pull_request_review:
    types: [submitted]
    branches-ignore: 'develop'

jobs:
  merge-if-approved:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: develop
    - run: |
          git merge ${{github.event.pull_request.head.label}}
    # - name: Merge PR into develop
    #   uses: devmasx/merge-branch@master
    #   with:
    #     type: now
    #     target_branch: develop
    #     message: Merge PR into develop
    #     github_token: ${{ secrets.GH_TOKEN }}
    #   env:
    #     GITHUB_SHA: ${{ github.event.pull_request.head.sha }}