# https://github.com/marketplace/actions/merge-branch
name: "Merge into develop on Approval"
on:
  pull_request_review:
    types: [submitted]
    branches-ignore: 'develop'

jobs:
  deploy-if-approved:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: ${{github.event.pull_request.head.sha}}

    - name: Merge PR into develop
      uses: devmasx/merge-branch@master
      with:
        type: now
        target_branch: develop
        message: Merge PR into develop
        github_token: ${{ secrets.GH_TOKEN }}