name: Clone PR from main to develop
on:
  pull_request:
    types: [opened]
    branches:
      - 'main'

jobs:
  auto-pull-request:
    name: PullRequestAction
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Derive from branch name
        run: |
            PR_BASE_LABEL=${{ github.event.pull_request.base.label}}
            PR_HEAD_LABEL=${{ github.event.pull_request.head.label}}
            echo "PULL_REQUEST_BASE_LABEL=${PR_BASE_LABEL}" >> $GITHUB_ENV
            echo "PULL_REQUEST_HEAD_LABEL=${PR_HEAD_LABEL}" >> $GITHUB_ENV
      - name: Test outputs
        run: |
          echo "Pull request base label: ${PULL_REQUEST_BASE_LABEL}"
          echo "Pull request head label: ${PULL_REQUEST_HEAD_LABEL}"
      - name: pull-request-action
        uses: vsoch/pull-request-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_BRANCH: "develop"
          PASS_IF_EXISTS: true