name: "Deploy to Staging on Approval"
on:
  pull_request_review:
    types: [submitted]
    branches-ignore: 'develop'

jobs:
  deploy-if-approved:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Merge PR into `develop`
      uses: devmasx/merge-branch@master
      with:
        type: now
        target_branch: develop
        message: Merge PR into develop
        github_token: ${{ secrets.GH_TOKEN }}